app_financas/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('transacoes', views.transacoes, name='transacoes'),
    path('cadastrar_transacao', views.cadastro_transacoes, name='nova_transacao'),
    path('transacoes_categorias/<categoria_id>', views.transacoes_por_cat, name='transacao_por_cat'), # Mostrar transações por cat
    path('categorias', views.categorias, name='categorias'), # Mostrar transações por cat
    path('nova_categoria', views.nova_categoria, name='nova_categoria'),
    path('processa_formulario', views.processa_formulario, name='processa_formulario') # teste de formularios novos
]

minhas_financas/urls.py
from django.contrib import admin
from django.urls import path, include
from app_financas import views

# include ->

urlpatterns = [
    path('admin/', admin.site.urls),
    path('transacoes/', views.transacoes),
    path('', include('app_financas.urls')),
]

app_financas/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

# Aqui criamos as coisas que vamos colocar no banco de dados, as informações que
# vamos armazenar no banco de dados
# classes ->  e criamos tabelas atraves das classes

class Usuario(models.Model):
    nome = models.CharField(max_length=50)


class Categoria(models.Model):
    data_criado_em = models.DateField(auto_now=True)
    nome = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.nome}'

class Transacao(models.Model):
    """
    Representa uma transação financeira no sistema.
    Atributos:
        data_criado_em (DateTimeField): Data e hora em que a transação foi criada. Atualizado automaticamente.
        descricao (CharField): Descrição da transação, com um limite de 50 caracteres.
        valor (FloatField): Valor monetário da transação.
        categoria (ForeignKey): Categoria associada à transação. Pode ser nula e utiliza SET_NULL ao ser excluída.
    Métodos:
        __str__(): Retorna uma representação em string da transação no formato 'dd/mm/aaaa - descricao'.
    """
    data_criado_em = models.DateTimeField(auto_now=True)
    data_transacao = models.DateTimeField(default=timezone.now)
    descricao = models.CharField(max_length=50)
    valor = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.data_criado_em.strftime("%d/%m/%Y")} - {self.descricao}'
    

app_financas/forms.py
from django import forms
from .models import Transacao


class TransacaoForm(forms.ModelForm):
    class Meta:
        model = Transacao
        fields = ['data_transacao','descricao','valor','categoria']
        labels = {
            'data_transacao':'Data Transação',
            'descricao': 'Descrição',
            'valor': 'Valor',
            'categoria': 'Categoria'
        }

app_financas/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Usuario, Categoria, Transacao # importanto a tabela
from .forms import TransacaoForm # o ponto é porque ta no mesmo arquivo
from django.urls import reverse
# Create your views here.

# aqui a gente vai criar a lógica atraves do site

# podemos definir as funções ou classes, pra usar aqui
# ex:. quando o usuário entrar no link de finanças, verificar se ele está logado
# caso ele não estiver jogar pra login .... etc
# (aqui vai ser o backend)

def index(request):
    '''Pagina principal das minhas finanças'''
    return render(request, 'index.html')


def home(request):
    if request.method == "GET":
        return render(request, 'home.html')
    else:
        nome = request.POST.get('nome')
        # return HttpResponse('Formulário enviado! %s ' % nome)
    
        user = Usuario(
            nome = nome
        )

        user.save()
    
        return HttpResponse(f'Formulário enviado! {nome}')
    

def transacoes(request):
    '''Mostra todas as transacoes registrada'''
    if request.method == 'GET':
        transacoes = Transacao.objects.order_by('data_transacao')
        context = {'transacoes': transacoes} # para retornar o contexto

        return render(request, 'transacoes.html', context=context)
    

def cadastro_transacoes(request):
    '''Adciona uma nova transação financeira.'''

    if request.method != 'POST':
        # Nenhum dado submetido
        form = TransacaoForm()  

    else:
        # Dados de POST submetidos, processa os dadas
        form = TransacaoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('transacoes'))
        
    context = {'form': form}
    return render(request, 'nova_transacao.html', context)


def transacoes_por_cat(request, categoria_id):
    '''Mostra as transações dentro de cada categoria'''
    
    categoria = Categoria.objects.get(id = categoria_id)
    transacoes = categoria.transacao_set.order_by('-data_criado_em')
    context = {'categoria': categoria, 'transacoes': transacoes}

    return render(request, 'transacoes_por_categora.html',context=context)


def categorias(request):
    '''lista todas as categorias'''

    categorias = Categoria.objects.all().order_by('data_criado_em')
    context = {'categorias': categorias}

    return render(request, 'categorias.html', context=context)



def nova_categoria(request):
    return render(request, 'nova_categoria.html')

def processa_formulario(request):

    nome = request.POST.get('nome')
    email = request.POST.get('email')
    return HttpResponse(f' {nome} -> {email}')

app_financas/templates/base.html
<a href="{% url 'index' %}">Minhas Finanças</a>
<a href="{% url 'transacoes' %}"><button type="button">Transacoes</button></a>
<a href="{% url 'nova_transacao' %}"><button type="button">Nova Transação</button></a>
<a href="{% url 'categorias' %}"><button type="button">Categorias</button></a>
<a href="{% url 'nova_categoria' %}"><button type="button">Nova Categoria</button></a>

{% block content %} {% endblock content %}

<footer>Desenvolvido por Gabriel Dagostim, 2025</footer>

app_financas/templates/categorias.html
{% extends 'base.html' %}

{% block content %}

{% for categoria in categorias %}
    <li>
        <a href="{% url 'transacao_por_cat' categoria.id %}">{{categoria}}</a>

    </li>

{% empty %}
    <li>
        <p>Não temos categorias adicionadas.</p>
    </li>
{% endfor %}

<a href="{% url 'nova_transacao' %}">Adcionar Transação</a>

{% endblock content %}

app_financas/templates/index.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="" rel="stylesheet">
    <title>Minhas Finanças</title>

    <style>
        .titulo {
            text-shadow: 2px 2px 5px gray;
        }
    </style>

</head>

<body>

    <div>
        {% extends "base.html" %}
    </div>

    {% block content %}

    <div>
        <p>App simples para gerir finanças pessoais de forma <b>simples</b> e <b>objetiva</b>.</p>
    </div>



    {% endblock content %}
</body>

</html>

app_financas/templates/nova_categoria.html
{% extends 'base.html' %}

{% block content %}



<br>
<form action="{% url 'processa_formulario' %}" method="post"> {% csrf_token %}
    <label>Nome:</label>
    <input type="text" placeholder="Nome" name="nome">

    <label>Email:</label>
    <input type="email" placeholder="Email" name="email">

    <input type="submit" value="Enviar">

</form>


{% endblock content %}

app_financas/templates/nova_transacao.html
{% extends 'base.html' %}

{% block content %}

<!-- <form action="{% url 'nova_transacao' %}" method="post"> 
        {% csrf_token %}      
        {{ form.as_p }}
        
        <button type="submit" name="submit">Adcionar Transacao</button>    
    -->

<form action="/cadastrar_transacao" method="post">        
    <p>
        <label for="id_descricao">Descrição:</label>
        <input type="text" name="descricao" maxlength="50" required="" id="id_descricao">
    </p>

    <p>
        <label for="id_valor">Valor:</label>
        <input type="number" name="valor" step="any" required="" id="id_valor">
    </p>

    <p>
        <label for="id_categoria">Categoria:</label>
        <select name="categoria" required="" id="id_categoria">
            <option value="" selected="">---------</option>

            <option value="1">Salário</option>

            <option value="2">Viagem</option>

            <option value="3">Investiment</option>
        </select>
    </p>

    <button class="button" type="submit" name="submit">Adicionar Transação</button>

</form>


{% endblock content %}

app_financas/templates/transacoes.html
{% extends "base.html" %}

{% block content %}

{% if transacoes %}
<table border="1">
    <thead>
        <tr>
            <th>Data Registro</th>
            <th>Data Transação</th>
            <th>Descrição</th>
            <th>Valor</th>
            <th>categoria</th>
        </tr>
    </thead>
    <tbody>
        {% for t in transacoes %}
            <tr>
                <td>{{ t.data_criado_em | date:"d/m/Y H:i" }}</td>
                <td>{{ t.data_transacao | date:"d/m/Y" }}</td>
                <td>{{ t.descricao | linebreaks}}</td>
                <td>{{ t.valor | floatformat:"2u"}}</td>
                <td>{{ t.categoria.nome}}</td>

            </tr>
        {% endfor %}
    </tbody>
</table>

{% else %}
    <p>Não há transacoes</p>

{% endif %}


<a href="{% url 'nova_transacao' %}">Adcionar Transação</a>

<br>
{% endblock content %}

app_financas/templates/transacoes_por_categora.html
{% extends "base.html" %}

{% block content %}

    <h3>Categoria: {{ categoria }}</h3>

    <p>🔄 Transações: </p>
    <ul>
        {% for t in transacoes %}
            <li>
                <p>{{ t.data_criado_em | date:"d/m/Y" }} {{ t.data_criado_em | date:"H:i" }}</p>
                <p>{{ t.descricao | linebreaks }}</p>
                <p>💸 {{ t.valor | floatformat:"2u" }}</p>
            </li>
        {% empty %}
            <li> Não há registros</li>
        {% endfor %}
    </ul>

{% endblock content %}